osoba(kazimierzIISprawiedliwy).
osoba(leszekBialy).
osoba(konradIMazowiecki).
osoba(boleslawVWstydliwy).
osoba(boleslaw).
osoba(kazimierzI).
osoba(siemowit).
osoba(leszekCzarny).
osoba(siemomysl).
osoba(wladyslawIlokietek).
osoba(kazimierzII).
osoba(siemowit).
osoba(leszek).
osoba(przemysl).
osoba(kazimierzIII).
osoba(kazimierzIIIWielki).
osoba(wladyslawGarbaty).
osoba(boleslaw).
osoba(wladyslawBialy).
rokSmierci(kazimierzIISprawiedliwy,1194).
rokSmierci(leszekBialy,1227).
rokSmierci(konradIMazowiecki,1247).
rokSmierci(boleslawVWstydliwy,1279).
rokSmierci(boleslaw,1248).
rokSmierci(kazimierzI,1267).
rokSmierci(siemowit,1262).
rokSmierci(leszekCzarny,1288).
rokSmierci(siemomysl,1287).
rokSmierci(wladyslawIlokietek,1333).
rokSmierci(kazimierzII,1294).
rokSmierci(siemowit,1312).
rokSmierci(leszek,1340).
rokSmierci(przemysl,1339).
rokSmierci(kazimierzIII,1347).
rokSmierci(kazimierzIIIWielki,1370).
rokSmierci(wladyslawGarbaty,1351).
rokSmierci(boleslaw,1328).
rokSmierci(wladyslawBialy,1388).
ojciecSyn(kazimierzIISprawiedliwy,leszekBialy).
ojciecSyn(kazimierzIISprawiedliwy,konradIMazowiecki).
ojciecSyn(konradIMazowiecki,boleslaw).
ojciecSyn(konradIMazowiecki,kazimierzI).
ojciecSyn(konradIMazowiecki,siemowit).
ojciecSyn(kazimierzI,leszekCzarny).
ojciecSyn(kazimierzI,siemomysl).
ojciecSyn(kazimierzI,wladyslawIlokietek).
ojciecSyn(kazimierzI,kazimierzII).
ojciecSyn(kazimierzI,siemowit).
ojciecSyn(siemomysl,leszek).
ojciecSyn(siemomysl,przemysl).
ojciecSyn(siemomysl,kazimierzIII).
ojciecSyn(kazimierzIII,wladyslawBialy).
ojciecSyn(wladyslawIlokietek,kazimierzIIIWielki).
ojciecSyn(siemowit,wladyslawGarbaty).
ojciecSyn(siemowit,boleslaw).
