kobieta(elzbietaII).
kobieta(kamila).
kobieta(kamilaate).
kobieta(karolina).
mezczyzna(filip).
mezczyzna(karol).
mezczyzna(wiliam).
mezczyzna(harry).
mezczyzna(jerzy).
malzenstwo(elzbietaII,filip).
malzenstwo(filip,elzbietaII).
malzenstwo(karol,kamila).
malzenstwo(kamila,karol).
malzenstwo(wiliam,kate).
malzenstwo(kate,wiliam).
rodzicDziecko(karol,wiliam).
rodzicDziecko(karol,harry).
rodzicDziecko(wiliam,jerzy).
rodzicDziecko(kate,jerzy).
rodzicDziecko(wiliam,karolina).
rodzicDziecko(kate,karolina).
