mezczyzna(wladyslawIIJagiello).
mezczyzna(wladyslawIIIWarnenczyk).
mezczyzna(kazimierz).
mezczyzna(kazimierzIVJagiellonczyk).
mezczyzna(wladyslawIIJagiellonczyk).
mezczyzna(jerzyBogaty).
mezczyzna(kazimierzJagiellonczyk).
mezczyzna(janIOlbracht).
mezczyzna(aleksanderJagiellonczyk).
mezczyzna(fryderykStarszyHohenzollern).
mezczyzna(ferdynandIHabsburg).
mezczyzna(ludwikIIJagiellonczyk).
mezczyzna(zygmuntIStary).
mezczyzna(fryderykJagiellonczyk).
mezczyzna(boguslawX).
mezczyzna(jerzySaski).
mezczyzna(fryderykII).
mezczyzna(joachimIIHektor).
mezczyzna(janZapolyia).
mezczyzna(zygmuntIIAugust).
mezczyzna(henrykII).
mezczyzna(stefanBatory).
mezczyzna(janIIIWaza).
mezczyzna(wojciechOlbracht).
kobieta(jadwigaAndegawenska).
kobieta(annaCylejska).
kobieta(elzbietaGrabowska).
kobieta(zofiaHolszanska).
kobieta(elzbietaBonifacja).
kobieta(jadwigaJagielonska).
kobieta(elzbietaRakuszanka).
kobieta(barbaraHohenzollem).
kobieta(beatryczeAragonska).
kobieta(annaDeFoix).
kobieta(jadwigaJagielonska).
kobieta(helenaMoskiewska).
kobieta(zofiaJagiellonka).
kobieta(elzbietaJagiellonkaI).
kobieta(annaJagiellonka).
kobieta(mariaHabsburzanka).
kobieta(barbaraZapolya).
kobieta(bonaSforza).
kobieta(elzbietaJagiellonkaII).
kobieta(annaJagielonnka).
kobieta(barbaraJagiellonka).
kobieta(elzbietaJagiellonkaIII).
kobieta(jadwigaJagielonska).
kobieta(anna).
kobieta(izabelaJagiellonka).
kobieta(elzbietaHabsbuzanka).
kobieta(barbaraRadziwillowna).
kobieta(katarzynaHabsbuzanka).
kobieta(zofiaJagiellonka).
kobieta(annaJagiellonka).
kobieta(katarzynaJagiellonka).
malzenstwo(katarzynaJagiellonka,janIIIWaza).
malzenstwo(annaJagiellonka,stefanBatory).
malzenstwo(zygmuntIIAugust,elzbietaHabsbuzanka).
malzenstwo(zygmuntIIAugust,barbaraRadziwillowna).
malzenstwo(zygmuntIIAugust,katarzynaHabsbuzanka).
malzenstwo(izabelaJagiellonka,janZapolyia).
malzenstwo(jadwigaJagielonska,joachimIIHektor).
malzenstwo(elzbietaJagiellonkaIII,fryderykII).
malzenstwo(barbaraJagiellonka,jerzySaski).
malzenstwo(annaJagiellonka,boguslawX).
malzenstwo(zygmuntIStary,barbaraZapolya).
malzenstwo(zygmuntIStary,bonaSforza).
malzenstwo(ludwikIIJagiellonczyk,mariaHabsburzanka).
malzenstwo(annaJagiellonka,ferdynandIHabsburg).
malzenstwo(wladyslawIIJagiellonczyk,barbaraHohenzollem).
malzenstwo(wladyslawIIJagiellonczyk,beatryczeAragonska).
malzenstwo(wladyslawIIJagiellonczyk,annaDeFoix).
malzenstwo(jadwigaJagielonska,jerzyBogaty).
malzenstwo(aleksanderJagiellonczyk,helenaMoskiewska).
malzenstwo(zofiaJagiellonka,fryderykStarszyHohenzollern).
malzenstwo(kazimierzIVJagiellonczyk,elzbietaRakuszanka).
malzenstwo(wladyslawIIJagiello,jadwigaAndegawenska).
malzenstwo(wladyslawIIJagiello,annaCylejska).
malzenstwo(wladyslawIIJagiello,elzbietaGrabowska).
malzenstwo(wladyslawIIJagiello,zofiaHolszanska).

malzenstwo(X,Y):-malzenstwo(Y,X).

rodzicDziecko(wladyslawIIJagiello,elzbietaBonifacja).
rodzicDziecko(wladyslawIIJagiello,jadwigaJagielonska).
rodzicDziecko(wladyslawIIJagiello,wladyslawIIIWarnenczyk).
rodzicDziecko(wladyslawIIJagiello,kazimierz).
rodzicDziecko(wladyslawIIJagiello,kazimierzIVJagiellonczyk).
rodzicDziecko(kazimierzIVJagiellonczyk,wladyslawIIJagiellonczyk).
rodzicDziecko(kazimierzIVJagiellonczyk,jadwigaJagielonska).
rodzicDziecko(kazimierzIVJagiellonczyk,kazimierzJagiellonczyk).
rodzicDziecko(kazimierzIVJagiellonczyk,janIOlbracht).
rodzicDziecko(kazimierzIVJagiellonczyk,aleksanderJagiellonczyk).
rodzicDziecko(kazimierzIVJagiellonczyk,zofiaJagiellonka).
rodzicDziecko(kazimierzIVJagiellonczyk,elzbietaJagiellonkaI).
rodzicDziecko(kazimierzIVJagiellonczyk,zygmuntIStary).
rodzicDziecko(kazimierzIVJagiellonczyk,fryderykJagiellonczyk).
rodzicDziecko(kazimierzIVJagiellonczyk,elzbietaJagiellonkaII).
rodzicDziecko(kazimierzIVJagiellonczyk,annaJagiellonka).
rodzicDziecko(kazimierzIVJagiellonczyk,barbaraJagiellonka).
rodzicDziecko(kazimierzIVJagiellonczyk,elzbietaJagiellonkaIII).
rodzicDziecko(wladyslawIIJagiellonczyk,annaJagiellonka).
rodzicDziecko(wladyslawIIJagiellonczyk,ludwikIIJagiellonczyk).
rodzicDziecko(zygmuntIStary,jadwigaJagielonska).
rodzicDziecko(zygmuntIStary,anna).
rodzicDziecko(zygmuntIStary,izabelaJagiellonka).
rodzicDziecko(zygmuntIStary,zygmuntIIAugust).
rodzicDziecko(zygmuntIStary,zofiaJagiellonka).
rodzicDziecko(zygmuntIStary,annaJagiellonka).
rodzicDziecko(zygmuntIStary,katarzynaJagiellonka).
rodzicDziecko(zygmuntIStary,wojciechOlbracht).
