przedmiot(stolik).
przedmiot(fotel).
przedmiot(pilot).
przedmiot(podkladka).
przedmiot(komoda).
przedmiot(wiezaHifi).
przedmiot(plytaCD).
przedmiot(stolikZszuflada).
przedmiot(szchownica).
przedmiot(sluchawki).
przedmiot(czapka).
przedmiot(kielich).
przedmiot(gazeta).
przedmiot(dywan).
stoiNa(dywan,stolik).
stoiNa(dywan, fotel).
stoiNa(fotel,sluchawki).
stoiNa(fotel,czapka).
stoiNa(stolik,pilot).
stoiNa(stolik,podkladka).
stoiNa(stolik,kielich).
stoiNa(stolik,gazeta).
stoiNa(stolikZszuflada,szachownica).
kolor(stolik,czarny).
kolor(fotel,brazowy).
kolor(komoda,brazowy).
kolor(stolikZszuflada,brazowy).
